import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import Logo from "@/public/images/UdvashUnmeshOnlineCare.png";
import Link from "next/link";
import { CiMenuBurger } from "react-icons/ci";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Dashboard - Udvash Unmesh Online Care",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="text-black bg-white">
          <nav className="bg-white px-4 py-2 shadow-md flex items-center justify-between">
            <div className="flex items-center gap-6">
              <Link href="/">
                <Image src={Logo} alt="Logo" className="h-12 w-auto" />
              </Link>
              <CiMenuBurger size={32} className="cursor-pointer" />
            </div>
            <div className="flex items-center gap-4">
              <Image
                src="https://ums-portal-3.osl.team/Content/Image/AppIcon/Notification.svg"
                alt="Notification Icon"
                width={32}
                height={32}
                className="cursor-pointer"
              />
              <Image
                src="https://ums-portal-3.osl.team/Content/Image/AppIcon/Profile.svg"
                alt="Profile Icon"
                width={32}
                height={32}
                className="cursor-pointer"
              />
            </div>
          </nav>

          <div className="flex">
            <aside>This is sidebar</aside>
            <main>{children}</main>
          </div>
        </div>
      </body>
    </html>
  );
}
