import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import Logo from "@/public/images/UdvashUnmeshOnlineCare.png";
import Link from "next/link";
import { CiMenuBurger } from "react-icons/ci";
import Navbar from "./components/Navbar";
import Sidebar from "./components/Sidebar";
import Footer from "./components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Dashboard - Udvash Unmesh Online Care",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="text-black bg-white flex flex-col h-screen">
          <Navbar />

          <div className="flex flex-1 overflow-hidden">
            <Sidebar />

            <main className="bg-[#DED4DE] flex-1 overflow-y-auto">
              {children}

              <Footer />
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}
